services:
  web:
    image: website
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - '3000:3000'
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
